#!/bin/bash
total 40
drwxr-xr-x 2 root root 249 Oct  3 07:10 .
drwxr-xr-x 4 root root  49 Oct  3 06:43 ..
-rwxr-xr-x 1 root root  34 Oct  3 06:43 0-hello_world
-rwxr-xr-x 1 root root  28 Oct  3 06:43 1-confused_smiley
-rwxr-xr-x 1 root root  28 Oct  3 06:43 2-hellofile
-rwxr-xr-x 1 root root  39 Oct  3 06:43 3-twofiles
-rwxr-xr-x 1 root root  29 Oct  3 06:43 4-lastlines
-rwxr-xr-x 1 root root  29 Oct  3 06:43 5-firstlines
-rwxr-xr-x 1 root root  36 Oct  3 06:43 6-third_line
-rwxr-xr-x 1 root root  99 Oct  3 06:43 7-file
-rwxr--r-- 1 root root  98 Oct  3 07:10 8-cwd_state
-rwxr--r-- 1 root root  86 Oct  3 07:00 \*\\'"Best School"\'\\*$\?\*\*\*\*\*:)
-rw-r--r-- 1 root root   0 Oct  3 07:11 ls_cwd_content
